### ISSUE TITLE
Read interface?

### ISSUE THREAD

**Issue by jackfirth** [royallthefourth/dotenv#1]
A `(read-dotenv path)` function that returned an `environment-variables?` value using [`make-environment-variables`](http://docs.racket-lang.org/reference/envvars.html#%28def._%28%28quote._~23~25kernel%29._make-environment-variables%29%29) would be useful. With that I could interact with dotenv files without mutating the current environment. For instance, I could write this:

```
(define (call/dotenv path f)
  (define env (read-dotenv path))
  (parameterize ([current-environment-variables env])
    (f)))
```

**Comment by royallthefourth** [comment]
Thanks for the suggestion. I want to tackle some of the cleanup recommendations you provided on the list, then this should make an easy and logical feature addition.

**Comment by jackfirth** [comment]
Great, thanks for the quick addition!

One quick note about package versioning and docs: Scribble provides a `@history[]` form that you can use inside `@defproc[]` to document that that the `dotenv-read` function was added in version 1.1 of your package. [Here's an example](https://github.com/jackfirth/racket-mock/blob/master/arguments/main.scrbl#L51) from one of my packages:

<img width="737" alt="screen shot 2017-08-29 at 5 46 17 pm" src="https://user-images.githubusercontent.com/8175575/29850389-279eedee-8ce2-11e7-89b3-62460d42748e.png">

**Comment by royallthefourth** [comment]
I didn't understand what the big deal with Scribble was at first. This is great!

**Comment by jackfirth** [comment]
Wait until you start using [`scribble/example`](http://docs.racket-lang.org/scribble/eval.html?q=scribble%2Fexamples) :)
