### ISSUE TITLE
Reduce library package footprint for deployment?

### ISSUE THREAD

**Issue by winny-** [royallthefourth/dotenv#5]
Hi, I've been looking into deploying an application and using this library, but noticed it depends on racket-doc, which appears to increase the `raco pkg install` time from 30 seconds to 3 minutes when working with a minimal racket installation.  It also increases the installation footprint by about 500 MB.

One could use a [multi-collection package](https://docs.racket-lang.org/pkg/Package_Concepts.html#%28tech._multi._collection._package%29) to avoid pulling in documentation for certain builds.  This might require splitting dotenv into something like `dotenv-lib`, `dotenv`, and `dotenv-doc` packages.  The [threading](https://github.com/lexi-lambda/threading) package does this, and it seems to do the trick (one simply installs `threading-lib`, instead of `threading` to get the library without documentation dependencies).

**Comment by royallthefourth** [comment]
Yikes! Not sure how I missed this. I'll split this soon.
